In [2]:
import torch

In [3]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
x = torch.Tensor([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

In [6]:
x.size() #Размер

torch.Size([3, 4])

In [7]:
x.shape #Тоже размер

torch.Size([3, 4])

In [8]:
x[0]

tensor([1., 2., 3., 4.])

In [9]:
x[0, 0]

tensor(1.)

In [10]:
x[:, 0]

tensor([1., 5., 9.])

In [11]:
x + 10 #Добавляет к каждому элементу тензора

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [12]:
x ** 2 #Каждый элемент в квадрат

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [13]:
y = torch.tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [14]:
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [15]:
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [16]:
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [17]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [18]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [19]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [20]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [21]:
x > 3 #Какие элементы тензора больше 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [22]:
mask = x > 3

In [23]:
x[mask] #Наложили маску и оставили только то, что подходит

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [24]:
x[x > 3] #Лишнюю переменную задавать не нужно

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

Реализуйте при помощи pyTorch функцию, которая возвращает сумму (x.sum()) элементов тензора X, строго превышающих значение limit, которое является входным значением алгоритма.

Входная матрица: X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [25]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = (X[X > limit]).sum()

print(larger_than_limit_sum)

1
tensor(44)


Неправильное копирование: объект y ссылается на ту же ячейку памяти что и объект x

In [26]:
y = x
y[0, 0] = 999
print(x)
print(y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


Правильное копирование:

In [27]:
x = torch.Tensor([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

In [28]:
y = x.clone()
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [29]:
x.dtype

torch.float32

In [30]:
x = x.double()
print(x)

x = x.int()
print(x)

x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [31]:
import numpy as np
x = np. array([[1, 2, 3, 4],
               [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [32]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [33]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [34]:
x = torch.rand([2, 3]) #Случайные числа от 0 до 1
x

tensor([[0.0209, 0.4180, 0.6413],
        [0.4787, 0.7143, 0.7403]])

In [35]:
torch.cuda.is_available() #Проверка включен ли GPU (Среда выполнения -> сменить среду выполнения)

True

In [36]:
torch.device('cuda:0') #Перевод расчета на видеокарту

device(type='cuda', index=0)

In [37]:
torch.device('cpu') #Перевод расчета на CPU

device(type='cpu')

In [38]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu') #Если есть GPU то на него, иначе CPU

In [39]:
x_cuda = x.to(device) #Тензор на GPU
x_cuda

tensor([[0.0209, 0.4180, 0.6413],
        [0.4787, 0.7143, 0.7403]], device='cuda:0')

In [40]:
%time y = (x - x + x * 10.0) ** 2 #Время на CPU

CPU times: user 993 µs, sys: 0 ns, total: 993 µs
Wall time: 675 µs


In [41]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2 #Время на GPU

CPU times: user 1.87 ms, sys: 255 µs, total: 2.13 ms
Wall time: 11 ms


Выигрыш по времени наблюдается для больших тензоров

In [42]:
x = torch.rand([2000, 3000])
x_cuda = x.to(device)
%time y = (x - x + x * 10.0) ** 2
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 18.7 ms, sys: 31.3 ms, total: 50 ms
Wall time: 50.2 ms
CPU times: user 1.7 ms, sys: 966 µs, total: 2.67 ms
Wall time: 1.44 ms
